AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  connpass-notifier
  
  SAM application to monitor connpass events and send email notifications

# Global values that apply to all resources
Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: python3.11
    Architectures:
      - x86_64
    Environment:
      Variables:
        EVENTS_TABLE_NAME: !Ref EventsTable
        CONNPASS_USER_ID: !Ref ConnpassUserId
        NOTIFICATION_EMAIL: !Ref NotificationEmail
        SENDER_EMAIL: !Ref SenderEmail

# Parameters for configuration
Parameters:
  ConnpassUserId:
    Type: String
    Description: Connpass user ID to monitor (e.g., your-username)
  NotificationEmail:
    Type: String
    Description: Email address to receive notifications
  SenderEmail:
    Type: String
    Description: Verified SES sender email address
  NotificationHoursBefore:
    Type: Number
    Default: 24
    Description: Hours before event to send notification

Resources:
  # DynamoDB table to store events
  EventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: connpass-events
      AttributeDefinitions:
        - AttributeName: event_id
          AttributeType: S
        - AttributeName: event_date
          AttributeType: S
      KeySchema:
        - AttributeName: event_id
          KeyType: HASH
        - AttributeName: event_date
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  # Lambda function to check for new events on connpass
  EventCheckerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/event-checker/
      Handler: app.lambda_handler
      Description: Checks connpass for upcoming events
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventsTable
      Events:
        ScheduledCheck:
          Type: Schedule
          Properties:
            Schedule: rate(6 hours)
            Description: Check connpass every 6 hours for new events
            Enabled: true

  # Lambda function to send email notifications
  EmailNotifierFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/email-notifier/
      Handler: app.lambda_handler
      Description: Sends email notifications for upcoming events
      Environment:
        Variables:
          NOTIFICATION_HOURS_BEFORE: !Ref NotificationHoursBefore
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventsTable
        - SESCrudPolicy:
            IdentityName: !Ref SenderEmail
      Events:
        ScheduledNotification:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
            Description: Check for upcoming events every hour
            Enabled: true

  # CloudWatch Log Groups
  EventCheckerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${EventCheckerFunction}
      RetentionInDays: 7

  EmailNotifierLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${EmailNotifierFunction}
      RetentionInDays: 7

Outputs:
  EventCheckerFunctionArn:
    Description: "Event Checker Lambda Function ARN"
    Value: !GetAtt EventCheckerFunction.Arn
  EmailNotifierFunctionArn:
    Description: "Email Notifier Lambda Function ARN"
    Value: !GetAtt EmailNotifierFunction.Arn
  EventsTableName:
    Description: "DynamoDB Events Table Name"
    Value: !Ref EventsTable
